package com.itdocx.oneapp.Models

data class dataofUser(
    var name: String? = null,
    var email: String? = null,
    val phoneNumber: String? = null,
    val cnic:String? = null,
    val address: String? = null,
    var walletCurrentbalance: String?=null,
    val uid: String? = null,
    val role:String ?=null
) {
    // No-argument constructor is either explicitly defined or automatically generated by Kotlin

    constructor() : this("", "", "", "","","0.00","","")

}
